src/main/default/objects/narrate_LogEvent__e/narrate_LogEvent__e.object-meta.xml
<CustomObject>
    <description>Log Events</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

src/main/default/objects/narrate_LoggingSetting__mdt/narrate_LoggingSetting__mdt.object-meta.xml
<CustomObject>
    <label>Logging Setting</label>
    <pluralLabel>Logging Settings</pluralLabel>
</CustomObject>

src/main/default/objects/narrate_LoggingSetting__mdt/fields/narrate_Active__c.field-meta.xml
<CustomField>
    <fullName>narrate_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/narrate_LoggingSetting__mdt/fields/narrate_Loggers__c.field-meta.xml
<CustomField>
    <fullName>narrate_Loggers__c</fullName>
    <label>Loggers</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LoggingSetting__mdt/fields/narrate_Logic__c.field-meta.xml
<CustomField>
    <fullName>narrate_Logic__c</fullName>
    <label>Logic</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/narrate_LoggingSettingsManager.cls
public without sharing class narrate_LoggingSettingsManager {
    
    @testVisible
    private static List<narrate_LoggingSetting__mdt> activeSettings {get {
        if(activeSettings==null) {
            activeSettings = [SELECT narrate_Logic__c, narrate_Loggers__c FROM narrate_LoggingSetting__mdt WHERE narrate_Active__c = true];
        }
        return activeSettings;
    } private set;}

    private static Map<Id, narrate_IFilterLogic> filtersBySettingsId {get {
        if(filtersBySettingsId == null) {
            filtersBySettingsId = new Map<Id, narrate_IFilterLogic>();
            for(narrate_LoggingSetting__mdt settings : activeSettings) {
                filtersBySettingsId.put(settings.Id, new narrate_SimpleFilterLogic(settings.narrate_Logic__c.split(' '))); //TODO???
            }
        }
        return filtersBySettingsId;
    } private set;}
    
    public static Set<String> getLoggerNamesForSettingsThatMatchFilter(narrate_LogEvent__e logData) {
        Set<String> result = new Set<String>();
        for(narrate_LoggingSetting__mdt setting : activeSettings) {
            if(filtersBySettingsId.get(setting.Id).evaluate(logData) && setting.narrate_Loggers__c != null) {
                result.addAll(setting.narrate_Loggers__c.split('[,;]'));
            }
        }
        return result;
    }
}