src/main/default/objects/narrate_LogEvent__e/narrate_LogEvent__e.object-meta.xml
<CustomObject>
    <description>Log Events</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Context__c.field-meta.xml
<CustomField>
    <fullName>narrate_Context__c</fullName>
    <label>Context</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Message__c.field-meta.xml
<CustomField>
    <fullName>narrate_Message__c</fullName>
    <label>Message</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/classes/narrate_LiveNotificationLogger.cls
public class narrate_LiveNotificationLogger extends narrate_SimpleLogger {
    override public Integer processEvents(List<narrate_LogEvent__e> logs) {
        Integer count = 0;
        List<FeedItem> feedItems = new List<FeedItem>();
        System.debug('LiveNotificationLogger ' + logs);
        for(narrate_LogEvent__e log : logs) {
            feedItems.add(new FeedItem(
                ParentId = '00555000004eY2mAAE',
                Body = log.narrate_Message__c,
                Title = log.narrate_Context__c
            ));
        }
        for(Database.SaveResult saveResult : Database.insert(feedItems, false)) {
            if(saveResult.isSuccess()) {
                count+=1;
            }
        }
        System.debug('count ' + count);
        return count;
    }
}