src/main/default/objects/narrate_LogEvent__e/narrate_LogEvent__e.object-meta.xml
<CustomObject>
    <description>Log Events</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Class__c.field-meta.xml
<CustomField>
    <fullName>narrate_Class__c</fullName>
    <label>Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Level__c.field-meta.xml
<CustomField>
    <fullName>narrate_Level__c</fullName>
    <defaultValue>&quot;DEBUG&quot;</defaultValue>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Line__c.field-meta.xml
<CustomField>
    <fullName>narrate_Line__c</fullName>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Message__c.field-meta.xml
<CustomField>
    <fullName>narrate_Message__c</fullName>
    <label>Message</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Method__c.field-meta.xml
<CustomField>
    <fullName>narrate_Method__c</fullName>
    <label>Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Quiddity__c.field-meta.xml
<CustomField>
    <fullName>narrate_Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Request__c.field-meta.xml
<CustomField>
    <fullName>narrate_Request__c</fullName>
    <label>Request</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>narrate_Timestamp__c</fullName>
    <label>Timestamp</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_User__c.field-meta.xml
<CustomField>
    <fullName>narrate_User__c</fullName>
    <label>User</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/narrators/narrate_PlatformEventNarrator.cls
public without sharing class narrate_PlatformEventNarrator implements narrate_INarrator {

    public narrate_PlatformEventNarrator() {}

    public void log(String level, String message, List<Object> values) {
        String formattedMessage = String.format(message, castToStringList(values));
        narrate_LogEvent__e logData = constructLogEvent(snapshot.snap(), level, formattedMessage);
        EventBus.publish(logData);
    }

    public void except(Exception error) {
        narrate_LogEvent__e logData = constructLogEvent(snapshot.snap(error), error);
        EventBus.publish(logData);
    }

    public void restRequest(RestRequest request) {
        narrate_LogEvent__e logData = constructLogEvent(snapshot.snap(), request);
        EventBus.publish(logData);
    }

    public void restResponse(RestResponse response) {
        narrate_LogEvent__e logData = constructLogEvent(snapshot.snap(), response);
        EventBus.publish(logData);
    }

    public void httpRequest(HttpRequest request) {
        narrate_LogEvent__e logData = constructLogEvent(snapshot.snap(), request);
        EventBus.publish(logData);
    }

    public void httpResponse(HttpResponse response) {
        narrate_LogEvent__e logData = constructLogEvent(snapshot.snap(), response);
        EventBus.publish(logData);
    }

    public void setCodeLocationSnapshot(narrate_CodeLocationSnapshot snapshot) {
        this.snapshot = snapshot;
    }

    // PRIVATE

    @testVisible
    private static narrate_LogEvent__e constructLogEvent(narrate_CodeLocationSnapshot.Snapshot codeLocation, String level, String message) {
        return new narrate_LogEvent__e(
            narrate_Class__c = codeLocation.theClass,
            narrate_Level__c = level,
            narrate_Line__c = codeLocation.theLine,
            narrate_Message__c = message,
            narrate_Method__c = codeLocation.theMethod,
            narrate_Quiddity__c = CURRENT_REQUEST_QUIDDITY,
            narrate_Request__c = CURRENT_REQUEST_ID,
            narrate_Timestamp__c = System.now(),
            narrate_User__c = UserInfo.getUserId()
        );
    }
    @testVisible
    private static narrate_LogEvent__e constructLogEvent(narrate_CodeLocationSnapshot.Snapshot codeLocation, Exception error) {
        return new narrate_LogEvent__e(
            narrate_Class__c = codeLocation.theClass,
            narrate_Level__c = Narrate.EXCEPT,
            narrate_Line__c = codeLocation.theLine,
            narrate_Message__c = error.getMessage(),
            narrate_Method__c = codeLocation.theMethod,
            narrate_Quiddity__c = CURRENT_REQUEST_QUIDDITY,
            narrate_Request__c = CURRENT_REQUEST_ID,
            narrate_Timestamp__c = System.now(),
            narrate_User__c = UserInfo.getUserId()
        );
    }
    @testVisible
    private static narrate_LogEvent__e constructLogEvent(narrate_CodeLocationSnapshot.Snapshot codeLocation, RestRequest request) {
        return new narrate_LogEvent__e(
            narrate_Class__c = codeLocation.theClass,
            narrate_Level__c = Narrate.REST,
            narrate_Line__c = codeLocation.theLine,
            narrate_Message__c = JSON.serialize(request),
            narrate_Method__c = codeLocation.theMethod,
            narrate_Quiddity__c = CURRENT_REQUEST_QUIDDITY,
            narrate_Request__c = CURRENT_REQUEST_ID,
            narrate_Timestamp__c = System.now(),
            narrate_User__c = UserInfo.getUserId()
        );
    }
    @testVisible
    private static narrate_LogEvent__e constructLogEvent(narrate_CodeLocationSnapshot.Snapshot codeLocation, RestResponse response) {
        return new narrate_LogEvent__e(
            narrate_Class__c = codeLocation.theClass,
            narrate_Level__c = Narrate.REST,
            narrate_Line__c = codeLocation.theLine,
            narrate_Message__c = JSON.serialize(response),
            narrate_Method__c = codeLocation.theMethod,
            narrate_Quiddity__c = CURRENT_REQUEST_QUIDDITY,
            narrate_Request__c = CURRENT_REQUEST_ID,
            narrate_Timestamp__c = System.now(),
            narrate_User__c = UserInfo.getUserId()
        );
    }
    @testVisible
    private static narrate_LogEvent__e constructLogEvent(narrate_CodeLocationSnapshot.Snapshot codeLocation, HttpRequest request) {
        return new narrate_LogEvent__e(
            narrate_Class__c = codeLocation.theClass,
            narrate_Level__c = Narrate.REST,
            narrate_Line__c = codeLocation.theLine,
            narrate_Message__c = request.toString(),
            narrate_Method__c = codeLocation.theMethod,
            narrate_Quiddity__c = CURRENT_REQUEST_QUIDDITY,
            narrate_Request__c = CURRENT_REQUEST_ID,
            narrate_Timestamp__c = System.now(),
            narrate_User__c = UserInfo.getUserId()
        );
    }
    @testVisible
    private static narrate_LogEvent__e constructLogEvent(narrate_CodeLocationSnapshot.Snapshot codeLocation, HttpResponse response) {
        return new narrate_LogEvent__e(
            narrate_Class__c = codeLocation.theClass,
            narrate_Level__c = Narrate.REST,
            narrate_Line__c = codeLocation.theLine,
            narrate_Message__c = response.toString(),
            narrate_Method__c = codeLocation.theMethod,
            narrate_Quiddity__c = CURRENT_REQUEST_QUIDDITY,
            narrate_Request__c = CURRENT_REQUEST_ID,
            narrate_Timestamp__c = System.now(),
            narrate_User__c = UserInfo.getUserId()
        );
    }
    private static List<String> castToStringList(List<Object> values) {
        List<String> result = new List<String>();
        if(values!= null) {
            for(Object value : values)
                result.add('' + value);
        }
        return result;
    }
    @testVisible
    private static final System.Request CURRENT_REQUEST = System.Request.getCurrent();
    private static final String CURRENT_REQUEST_ID {get {
        if(CURRENT_REQUEST_ID==null){
            CURRENT_REQUEST_ID = CURRENT_REQUEST.getRequestId();
        }
        return CURRENT_REQUEST_ID;
    } private set;}
    private static final String CURRENT_REQUEST_QUIDDITY {get {
        if(CURRENT_REQUEST_QUIDDITY==null){
            CURRENT_REQUEST_QUIDDITY = String.valueOf(CURRENT_REQUEST.getQuiddity());
        }
        return CURRENT_REQUEST_QUIDDITY;
    } private set;}
    @testVisible
    private narrate_CodeLocationSnapshot snapshot;
}