src/main/default/objects/narrate_ExecutionContext__c/narrate_ExecutionContext__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Log Context</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/narrate_ExecutionContext__c/fields/narrate_EndTime__c.field-meta.xml
<CustomField>
    <fullName>narrate_EndTime__c</fullName>
    <label>End Time</label>
    <summarizedField>narrate_LogEntry__c.narrate_Timestamp__c</summarizedField>
    <summaryForeignKey>narrate_LogEntry__c.narrate_ExecutionContext__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/narrate_ExecutionContext__c/fields/narrate_NumberOfEntries__c.field-meta.xml
<CustomField>
    <fullName>narrate_NumberOfEntries__c</fullName>
    <label>Number of Entries</label>
    <summaryForeignKey>narrate_LogEntry__c.narrate_ExecutionContext__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/narrate_ExecutionContext__c/fields/narrate_StartTime__c.field-meta.xml
<CustomField>
    <fullName>narrate_StartTime__c</fullName>
    <label>Start Time</label>
    <summarizedField>narrate_LogEntry__c.CreatedDate</summarizedField>
    <summaryForeignKey>narrate_LogEntry__c.narrate_ExecutionContext__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/narrate_LogEntry__c.object-meta.xml
<CustomObject>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/narrate_LogEntry__c/fields/ExecutionContext__c.field-meta.xml
<CustomField>
    <fullName>ExecutionContext__c</fullName>
    <label>Log</label>
    <referenceTo>narrate_ExecutionContext__c</referenceTo>
    <relationshipLabel>Log Entries</relationshipLabel>
    <relationshipName>narrate_LogEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Class__c.field-meta.xml
<CustomField>
    <fullName>narrate_Class__c</fullName>
    <label>Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Context__c.field-meta.xml
<CustomField>
    <fullName>narrate_Context__c</fullName>
    <label>Unique Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_ExecutionContext__c.field-meta.xml
<CustomField>
    <fullName>narrate_ExecutionContext__c</fullName>
    <label>Log</label>
    <referenceTo>narrate_ExecutionContext__c</referenceTo>
    <relationshipLabel>Log Entries</relationshipLabel>
    <relationshipName>narrate_LogEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Level__c.field-meta.xml
<CustomField>
    <fullName>narrate_Level__c</fullName>
    <defaultValue>&quot;DEBUG&quot;</defaultValue>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Line__c.field-meta.xml
<CustomField>
    <fullName>narrate_Line__c</fullName>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Message__c.field-meta.xml
<CustomField>
    <fullName>narrate_Message__c</fullName>
    <label>Message</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Method__c.field-meta.xml
<CustomField>
    <fullName>narrate_Method__c</fullName>
    <label>Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_User__c.field-meta.xml
<CustomField>
    <fullName>narrate_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>narrate_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/classes/narrate_Query.cls
public with sharing class narrate_Query {
    public static List<narrate_ExecutionContext__c> loadLogsByExecutionContext(Set<String> contexts) {
        return [SELECT Id, Name FROM narrate_ExecutionContext__c WHERE Name IN :contexts];
    }

    @AuraEnabled(cacheable=true)
    public static narrate_ExecutionContext__c loadExecutionContextsWithLogs(String logId) {
        return [SELECT Id, Name, narrate_NumberOfEntries__c, narrate_StartTime__c, narrate_EndTime__c, (SELECT Id, Name, narrate_Class__c, narrate_Context__c, narrate_Level__c, narrate_Line__c, narrate_ExecutionContext__c, narrate_Message__c, narrate_Method__c, narrate_User__c FROM narrate_LogEntries__r) FROM narrate_ExecutionContext__c WHERE Id = :logId LIMIT 1];
    }

    public static Map<Id, User> loadUsersByIDs(Set<Id> ids) {
        return new Map<Id, User>([SELECT Email FROM User WHERE Id IN :ids]);
    }
}