src/main/default/objects/narrate_ExecutionContext__c/narrate_ExecutionContext__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Log Context</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/narrate_ExecutionContext__c/fields/narrate_Quiddity__c.field-meta.xml
<CustomField>
    <fullName>narrate_Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_ExecutionContext__c/fields/narrate_Request__c.field-meta.xml
<CustomField>
    <fullName>narrate_Request__c</fullName>
    <label>Request</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/narrate_LogEntry__c.object-meta.xml
<CustomObject>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Class__c.field-meta.xml
<CustomField>
    <fullName>narrate_Class__c</fullName>
    <label>Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_ExecutionContext__c.field-meta.xml
<CustomField>
    <fullName>narrate_ExecutionContext__c</fullName>
    <label>Log</label>
    <referenceTo>narrate_ExecutionContext__c</referenceTo>
    <relationshipLabel>Log Entries</relationshipLabel>
    <relationshipName>narrate_LogEntries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Level__c.field-meta.xml
<CustomField>
    <fullName>narrate_Level__c</fullName>
    <defaultValue>&quot;DEBUG&quot;</defaultValue>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Line__c.field-meta.xml
<CustomField>
    <fullName>narrate_Line__c</fullName>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Message__c.field-meta.xml
<CustomField>
    <fullName>narrate_Message__c</fullName>
    <label>Message</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Method__c.field-meta.xml
<CustomField>
    <fullName>narrate_Method__c</fullName>
    <label>Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Quiddity__c.field-meta.xml
<CustomField>
    <fullName>narrate_Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Request__c.field-meta.xml
<CustomField>
    <fullName>narrate_Request__c</fullName>
    <label>Request</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>narrate_Timestamp__c</fullName>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/narrate_LogEntry__c/fields/narrate_User__c.field-meta.xml
<CustomField>
    <fullName>narrate_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>narrate_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/narrate_LogEvent__e.object-meta.xml
<CustomObject>
    <description>Log Events</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Class__c.field-meta.xml
<CustomField>
    <fullName>narrate_Class__c</fullName>
    <label>Class</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Level__c.field-meta.xml
<CustomField>
    <fullName>narrate_Level__c</fullName>
    <defaultValue>&quot;DEBUG&quot;</defaultValue>
    <label>Level</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Line__c.field-meta.xml
<CustomField>
    <fullName>narrate_Line__c</fullName>
    <label>Line</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Message__c.field-meta.xml
<CustomField>
    <fullName>narrate_Message__c</fullName>
    <label>Message</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Method__c.field-meta.xml
<CustomField>
    <fullName>narrate_Method__c</fullName>
    <label>Method</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Quiddity__c.field-meta.xml
<CustomField>
    <fullName>narrate_Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Request__c.field-meta.xml
<CustomField>
    <fullName>narrate_Request__c</fullName>
    <label>Request</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>narrate_Timestamp__c</fullName>
    <label>Timestamp</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

src/main/default/objects/narrate_LogEvent__e/fields/narrate_User__c.field-meta.xml
<CustomField>
    <fullName>narrate_User__c</fullName>
    <label>User</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/loggers/narrate_RecordLogger.cls
public with sharing class narrate_RecordLogger implements narrate_ILogger {
    public Integer log(List<narrate_LogEvent__e> events) {
        Integer count = 0;
        try{
            Map<String, narrate_ExecutionContext__c> executionContextsByRequest = createExecutionContextsForLogEvents(events);
            Map<String, narrate_ExecutionContext__c> preexistingExecutionContexts = loadExecutionContextsByRequest(executionContextsByRequest.keySet());
            executionContextsByRequest.putAll(preexistingExecutionContexts);
            upsert executionContextsByRequest.values();
            List<narrate_LogEntry__c> logEntries = createLogEntriesForLogEvents(events, executionContextsByRequest);
            for(Database.SaveResult saveResult : Database.insert(logEntries)) {
                if(saveResult.isSuccess()) {
                    count+=1;
                }
            }
        }catch(Exception error){
            throw new narrate_NarratorException(error, 'narrate_RecordLogger');
        }
        return count;
    }

    @testVisible
    private List<narrate_LogEntry__c> createLogEntriesForLogEvents(List<narrate_LogEvent__e> events, Map<String, narrate_ExecutionContext__c> executionContextsByRequest){
        List<narrate_LogEntry__c> entries = new List<narrate_LogEntry__c>();
        for(narrate_LogEvent__e event : events){
            narrate_ExecutionContext__c execContext = executionContextsByRequest.get(event.narrate_Request__c);
            entries.add(constructEntryFromEvent(event, execContext?.Id));
        }
        return entries;
    }

    @testVisible
    private static narrate_LogEntry__c constructEntryFromEvent(narrate_LogEvent__e logEvent, Id executionContextId) {
        return new narrate_LogEntry__c(
            narrate_Class__c = logEvent.narrate_Class__c,
            narrate_ExecutionContext__c = executionContextId,
            narrate_Level__c = logEvent.narrate_Level__c,
            narrate_Line__c = logEvent.narrate_Line__c,
            narrate_Message__c = logEvent.narrate_Message__c,
            narrate_Method__c = logEvent.narrate_Method__c,
            narrate_Quiddity__c = logEvent.narrate_Quiddity__c,
            narrate_Timestamp__c = logEvent.narrate_Timestamp__c,
            narrate_User__c = logEvent.narrate_User__c
        );
    }

    @testVisible
    private Map<String, narrate_ExecutionContext__c> createExecutionContextsForLogEvents(List<narrate_LogEvent__e> events){
        Map<String, narrate_ExecutionContext__c> result = new Map<String, narrate_ExecutionContext__c>();
        for(narrate_LogEvent__e event : events){
            result.put(event.narrate_Request__c, new narrate_ExecutionContext__c(narrate_Request__c = event.narrate_Request__c, narrate_Quiddity__c = event.narrate_Quiddity__c));
        }
        return result;
    }

    @testVisible
    private static Map<String, narrate_ExecutionContext__c> loadExecutionContextsByRequest(Set<String> requests) {
        Map<String, narrate_ExecutionContext__c> result = new Map<String, narrate_ExecutionContext__c>();
        List<narrate_ExecutionContext__c> execs = [SELECT Id, Name, narrate_Request__c, narrate_Quiddity__c FROM narrate_ExecutionContext__c WHERE narrate_Request__c IN :requests];
        for(narrate_ExecutionContext__c exec : execs){
            result.put(exec.narrate_Request__c, exec);
        }
        return result;
    }
}